### ISSUE TITLE
Move compact layout and record data call to UI API

### ISSUE THREAD

**Issue by muenzpraeger** [trailheadapps/redwoods-insurance#17]
https://developer.salesforce.com/docs/atlas.en-us.uiapi.meta/uiapi/ui_api_resources_record_ui.htm

**Comment by muenzpraeger** [comment]
@codefriar What's the status of this?

**Comment by codefriar** [comment]
@muenzpraeger  - this was resolved, but the issue never closed.  See 
https://github.com/trailheadapps/redwoods-insurance/blob/master/redwoods-insurance-mobile/redwoods-insurance/ObjectLayoutDataSource.swift#L100
for more info. closing.
