### ISSUE TITLE
Apply SLDS best practices to components

### ISSUE THREAD

**Issue by muenzpraeger** [trailheadapps/redwoods-insurance#89]
**What is missing from the application? Please describe.**
To reflect UI development best practices the sample app needs to make use of SLDS design tokens that make use of the UI density settings in an org. Similar to that any manual CSS should be replaced, where it makes sense, with SLDS classes instead.
    
**Describe the solution you'd like**
Validate all Lightning web components (and Aura, if applicable) if they make use of the latest SLDS design tokens, and if manual CSS syntax needs to be updated with SLDS classes.

The [SLDS Validator](https://marketplace.visualstudio.com/items?itemName=salesforce.salesforce-vscode-slds) provides the needed analysis and correction capabilities.

**Comment by codefriar** [comment]
@muenzpraeger  - there's only a single css file, containing a single directive that is unrelated to SLDS. Your initial issue includes the phrase 'where it makes sense' and my current read of this is that it does not make sense to change this width directive to an SLDS constant. Please advise

**Comment by muenzpraeger** [comment]
The usage of the SLDS class would mean that we could get rid of the unnecessary CSS file.

**Comment by codefriar** [comment]
closed by #96
